package com.jfinal.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMistake<M extends BaseMistake<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setSno(java.lang.String Sno) {
		set("Sno", Sno);
	}
	
	public java.lang.String getSno() {
		return getStr("Sno");
	}
	
	public void setQno(java.lang.String Qno) {
		set("Qno", Qno);
	}
	
	public java.lang.String getQno() {
		return getStr("Qno");
	}
	
	public void setWorkFrequency(java.lang.Integer workFrequency) {
		set("work_frequency", workFrequency);
	}
	
	public java.lang.Integer getWorkFrequency() {
		return getInt("work_frequency");
	}
	
	public void setWrongFrequency(java.lang.Integer wrongFrequency) {
		set("wrong_frequency", wrongFrequency);
	}
	
	public java.lang.Integer getWrongFrequency() {
		return getInt("wrong_frequency");
	}
	
	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}
	
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
}

