package com.jfinal.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExam<M extends BaseExam<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setExamName(java.lang.String examName) {
		set("exam_name", examName);
	}
	
	public java.lang.String getExamName() {
		return getStr("exam_name");
	}
	
	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}
	
	public java.util.Date getStartDate() {
		return getDate("start_date");
	}
	
	public void setStartTime(java.sql.Time startTime) {
		set("start_time", startTime);
	}
	
	public java.sql.Time getStartTime() {
		return get("start_time");
	}
	
	public void setDuration(java.sql.Time duration) {
		set("duration", duration);
	}
	
	public java.sql.Time getDuration() {
		return get("duration");
	}
	
	public void setCourseName(java.lang.String courseName) {
		set("course_name", courseName);
	}
	
	public java.lang.String getCourseName() {
		return getStr("course_name");
	}
	
	public void setPaperId(java.lang.Integer paperId) {
		set("paper_id", paperId);
	}
	
	public java.lang.Integer getPaperId() {
		return getInt("paper_id");
	}
	
	public void setTotalScore(java.lang.Integer totalScore) {
		set("totalScore", totalScore);
	}
	
	public java.lang.Integer getTotalScore() {
		return getInt("totalScore");
	}
	
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}
	
	public void setExamDescription(java.lang.String examDescription) {
		set("exam_description", examDescription);
	}
	
	public java.lang.String getExamDescription() {
		return getStr("exam_description");
	}
	
	public void setAccountId(java.lang.Integer accountId) {
		set("account_id", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("account_id");
	}
	
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public void setQuestionScores(java.lang.String questionScores) {
		set("question_scores", questionScores);
	}
	
	public java.lang.String getQuestionScores() {
		return getStr("question_scores");
	}
	
	public void setAnswer(java.lang.String answer) {
		set("answer", answer);
	}
	
	public java.lang.String getAnswer() {
		return getStr("answer");
	}
	
	public void setChoiceAnswer(java.lang.String choiceAnswer) {
		set("choiceAnswer", choiceAnswer);
	}
	
	public java.lang.String getChoiceAnswer() {
		return getStr("choiceAnswer");
	}
	
}

