package com.jfinal.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExam<M extends BaseExam<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setExamName(java.lang.String examName) {
		set("exam_name", examName);
	}
	
	public java.lang.String getExamName() {
		return getStr("exam_name");
	}
	
	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}
	
	public java.util.Date getStartTime() {
		return getDate("start_time");
	}
	
	public void setLastTime(java.sql.Time lastTime) {
		set("last_time", lastTime);
	}
	
	public java.sql.Time getLastTime() {
		return get("last_time");
	}
	
	public void setCourseName(java.lang.String courseName) {
		set("course_name", courseName);
	}
	
	public java.lang.String getCourseName() {
		return getStr("course_name");
	}
	
	public void setPaperId(java.lang.Integer paperId) {
		set("paper_id", paperId);
	}
	
	public java.lang.Integer getPaperId() {
		return getInt("paper_id");
	}
	
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}
	
	public void setExamDescription(java.lang.String examDescription) {
		set("exam_description", examDescription);
	}
	
	public java.lang.String getExamDescription() {
		return getStr("exam_description");
	}
	
	public void setAccountId(java.lang.Integer accountId) {
		set("account_id", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("account_id");
	}
	
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public void setQuestionScores(java.lang.String questionScores) {
		set("question_scores", questionScores);
	}
	
	public java.lang.String getQuestionScores() {
		return getStr("question_scores");
	}
	
}

