package com.jfinal.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePaper<M extends BasePaper<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setPno(java.lang.Integer Pno) {
		set("Pno", Pno);
	}
	
	public java.lang.Integer getPno() {
		return getInt("Pno");
	}
	
	public void setQno(java.lang.Integer Qno) {
		set("Qno", Qno);
	}
	
	public java.lang.Integer getQno() {
		return getInt("Qno");
	}
	
	public void setTime(java.lang.Integer time) {
		set("time", time);
	}
	
	public java.lang.Integer getTime() {
		return getInt("time");
	}
	
	public void setAccountId(java.lang.Integer AccountId) {
		set("AccountId", AccountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("AccountId");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public void setFileName(java.lang.String FileName) {
		set("FileName", FileName);
	}
	
	public java.lang.String getFileName() {
		return getStr("FileName");
	}
	
	public void setShowName(java.lang.String ShowName) {
		set("ShowName", ShowName);
	}
	
	public java.lang.String getShowName() {
		return getStr("ShowName");
	}
	
	public void setPath(java.lang.String Path) {
		set("Path", Path);
	}
	
	public java.lang.String getPath() {
		return getStr("Path");
	}
	
	public void setLength(java.lang.Integer Length) {
		set("Length", Length);
	}
	
	public java.lang.Integer getLength() {
		return getInt("Length");
	}
	
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}
	
}

