package com.jfinal.admin.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.Integer getId() {
        return getInt("id");
    }

    public void setTno(java.lang.String Tno) {
        set("Tno", Tno);
    }

    public java.lang.String getTno() {
        return getStr("Tno");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.String getName() {
        return getStr("name");
    }

    public void setGender(java.lang.String gender) {
        set("gender", gender);
    }

    public java.lang.String getGender() {
        return getStr("gender");
    }

    public void setCollege(java.lang.String college) {
        set("college", college);
    }

    public java.lang.String getCollege() {
        return getStr("college");
    }

    public void setPicture(byte[] picture) {
        set("picture", picture);
    }

    public byte[] getPicture() {
        return get("picture");
    }

    public void setPhoneno(java.lang.String phoneno) {
        set("phoneno", phoneno);
    }

    public java.lang.String getPhoneno() {
        return getStr("phoneno");
    }

    public void setUpdateTime(java.util.Date updateTime) {
        set("update_time", updateTime);
    }

    public java.util.Date getUpdateTime() {
        return getDate("update_time");
    }

}

