package com.jfinal.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setSno(java.lang.String Sno) {
		set("Sno", Sno);
	}
	
	public java.lang.String getSno() {
		return getStr("Sno");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}
	
	public void setGender(java.lang.String gender) {
		set("gender", gender);
	}
	
	public java.lang.String getGender() {
		return getStr("gender");
	}
	
	public void setCollege(java.lang.String college) {
		set("college", college);
	}
	
	public java.lang.String getCollege() {
		return getStr("college");
	}
	
	public void setMajor(java.lang.String major) {
		set("major", major);
	}
	
	public java.lang.String getMajor() {
		return getStr("major");
	}
	
	public void setPicture(byte[] picture) {
		set("picture", picture);
	}
	
	public byte[] getPicture() {
		return get("picture");
	}
	
	public void setPhoneno(java.lang.String phoneno) {
		set("phoneno", phoneno);
	}
	
	public java.lang.String getPhoneno() {
		return getStr("phoneno");
	}
	
	public void setClassno(java.lang.String classno) {
		set("classno", classno);
	}
	
	public java.lang.String getClassno() {
		return getStr("classno");
	}
	
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
}

