package com.jfinal.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEvaluation<M extends BaseEvaluation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setQno(java.lang.String Qno) {
		set("Qno", Qno);
	}
	
	public java.lang.String getQno() {
		return getStr("Qno");
	}
	
	public void setUno(java.lang.String Uno) {
		set("Uno", Uno);
	}
	
	public java.lang.String getUno() {
		return getStr("Uno");
	}
	
	public void setEvaluation(java.lang.Integer evaluation) {
		set("evaluation", evaluation);
	}
	
	public java.lang.Integer getEvaluation() {
		return getInt("evaluation");
	}
	
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
}

