package com.jfinal.admin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuestion<M extends BaseQuestion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setCourseName(java.lang.String courseName) {
		set("course_name", courseName);
	}
	
	public java.lang.String getCourseName() {
		return getStr("course_name");
	}
	
	public void setUnit(java.lang.Integer unit) {
		set("unit", unit);
	}
	
	public java.lang.Integer getUnit() {
		return getInt("unit");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setInvolvement(java.lang.String involvement) {
		set("involvement", involvement);
	}
	
	public java.lang.String getInvolvement() {
		return getStr("involvement");
	}
	
	public void setAccountId(java.lang.Integer AccountId) {
		set("AccountId", AccountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("AccountId");
	}
	
	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}
	
	public void setEvaluation(java.lang.Integer evaluation) {
		set("evaluation", evaluation);
	}
	
	public java.lang.Integer getEvaluation() {
		return getInt("evaluation");
	}
	
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}
	
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}
	
	public void setQuestion(java.lang.String question) {
		set("question", question);
	}
	
	public java.lang.String getQuestion() {
		return getStr("question");
	}
	
	public void setAnswer(java.lang.String answer) {
		set("answer", answer);
	}
	
	public java.lang.String getAnswer() {
		return getStr("answer");
	}
	
	public void setOption(java.lang.String option) {
		set("option", option);
	}
	
	public java.lang.String getOption() {
		return getStr("option");
	}
	
}

