package com.jfinal.admin.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuestionChoice<M extends BaseQuestionChoice<M>> extends Model<M> implements IBean {

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.Integer getId() {
        return getInt("id");
    }

    public void setQno(java.lang.String Qno) {
        set("Qno", Qno);
    }

    public java.lang.String getQno() {
        return getStr("Qno");
    }

    public void setContent(java.lang.String content) {
        set("content", content);
    }

    public java.lang.String getContent() {
        return getStr("content");
    }

    public void setChoiceOption(java.lang.String choiceOption) {
        set("choice_option", choiceOption);
    }

    public java.lang.String getChoiceOption() {
        return getStr("choice_option");
    }

    public void setAnswer(java.lang.String answer) {
        set("answer", answer);
    }

    public java.lang.String getAnswer() {
        return getStr("answer");
    }

    public void setUpdateTime(java.util.Date updateTime) {
        set("update_time", updateTime);
    }

    public java.util.Date getUpdateTime() {
        return getDate("update_time");
    }

}

