package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseAdministrator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Administrator extends BaseAdministrator<Administrator> {
	
}

