package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseCourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Course extends BaseCourse<Course> {

}

