package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseCourseSelection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CourseSelection extends BaseCourseSelection<CourseSelection> {
	
}

