package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {
	
}

