package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseMistake;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mistake extends BaseMistake<Mistake> {
	
}

