package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BasePaper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Paper extends BasePaper<Paper> {
	
}

