package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {

}
