package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseQuestionChoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionChoice extends BaseQuestionChoice<QuestionChoice> {
	
}

