package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Question extends BaseQuestion<Question> {
	
}

