package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseScore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Score extends BaseScore<Score> {

}

