package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Session extends BaseSession<Session> {

}
