package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Student extends BaseStudent<Student> {

}

