package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseTeaching;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teaching extends BaseTeaching<Teaching> {
	
}

