package com.jfinal.admin.common.model;

import com.jfinal.admin.common.model.base.BaseTeacher;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacher extends BaseTeacher<Teacher> {
	
}

